return {
	["Introduction"] = {
		"Processed/Introduction/Ah.mp3",
		"Processed/Introduction/After i checked my body.mp3",
		"Processed/Introduction/As soon as i set foot.mp3",
		"Processed/Introduction/Gosh i apologize.mp3",
		"Processed/Introduction/I miss you so much.mp3",
		"Processed/Introduction/I think i saw a glimpse.mp3",
		"Processed/Introduction/I winced.mp3",
		"Processed/Introduction/I woke up.mp3",
		"Processed/Introduction/Ill discuss what.mp3",
		"Processed/Introduction/Im being held.mp3",
		"Processed/Introduction/She repeated that.mp3",
		"Processed/Introduction/She tidies her.mp3",
		"Processed/Introduction/Soon after.mp3",
		"Processed/Introduction/This body im in.mp3",
		"Processed/Introduction/Yes i know.mp3",
		"Processed/Introduction/that pains me.mp3",
		"Processed/Introduction/you cant go outside yet.mp3",
	},

	["Dining table"] = {
		"Processed/Dining table/AAHG.mp3",
		"Processed/Dining table/wince forward hard.mp3",
		"Processed/Dining table/Are you okay.mp3",
		"Processed/Dining table/Babe my love.mp3",
		"Processed/Dining table/not a single window.mp3",
		"Processed/Dining table/I dont want.mp3",
		"Processed/Dining table/I feel completely.mp3",
		"Processed/Dining table/I sat by.mp3",
		"Processed/Dining table/I saw her.mp3",
		"Processed/Dining table/If you live.mp3",
		"Processed/Dining table/Miss carmine finished.mp3",
		"Processed/Dining table/Miss carmines hand.mp3",
		"Processed/Dining table/She deeply sighed.mp3",
		"Processed/Dining table/She grabbed my hand.mp3",
		"Processed/Dining table/She quickly stood.mp3",
		"Processed/Dining table/She scoops a.mp3",
		"Processed/Dining table/So how about.mp3",
		"Processed/Dining table/Sopas.mp3",
		"Processed/Dining table/That seems easy.mp3",
		"Processed/Dining table/Then I steadily.mp3",
		"Processed/Dining table/The other doctors.mp3",
		"Processed/Dining table/When I finally.mp3",
		"Processed/Dining table/Yes i still.mp3",
	},

	["Laboratory"] = {
		"Processed/Laboratory/she fiercely pulled me.mp3",
		"Processed/Laboratory/I opened my.mp3",
		"Processed/Laboratory/a homunculus.mp3",
		"Processed/Laboratory/being one of the.mp3",
		"Processed/Laboratory/that my back suddenly felt.mp3",
		"Processed/Laboratory/did you change.mp3",
		"Processed/Laboratory/her tone sounds.mp3",
		"Processed/Laboratory/her voice caught.mp3",
		"Processed/Laboratory/however i felt a slight.mp3",
		"Processed/Laboratory/however no on.mp3",
		"Processed/Laboratory/i dont get.mp3",
		"Processed/Laboratory/i examined every.mp3",
		"Processed/Laboratory/its texture felt slightly.mp3",
		"Processed/Laboratory/i find it cute.mp3",
		"Processed/Laboratory/i finished the test.mp3",
		"Processed/Laboratory/i got ejected.mp3",
		"Processed/Laboratory/i had to.mp3",
		"Processed/Laboratory/i just need you.mp3",
		"Processed/Laboratory/i noticed her.mp3",
		"Processed/Laboratory/i was completely.mp3",
		"Processed/Laboratory/miss carmine doesnt.mp3",
		"Processed/Laboratory/my other senses.mp3",
		"Processed/Laboratory/no one matches.mp3",
		"Processed/Laboratory/not only that but.mp3",
		"Processed/Laboratory/one thing for.mp3",
		"Processed/Laboratory/perplexed i checked around.mp3",
		"Processed/Laboratory/she looked at both.mp3",
		"Processed/Laboratory/she gave me a thin.mp3",
		"Processed/Laboratory/she grabbed.mp3",
		"Processed/Laboratory/so how is it.mp3",
		"Processed/Laboratory/sorry for letting you.mp3",
		"Processed/Laboratory/this excruciating pain.mp3",
		"Processed/Laboratory/well lets cut.mp3",
		"Processed/Laboratory/what i saw.mp3",
		"Processed/Laboratory/what is holding steady.mp3",
		"Processed/Laboratory/you dedicated.mp3",
		"Processed/Laboratory/you mean this.mp3",
		"Processed/Laboratory/it was full of.mp3",
	},

	["Misc"] = {
		"Processed/Misc/Carmine gasp.mp3",
	},
}
